### PR TITLE
S14.00 bug sample db persistence

### LINKED ISSUE #201: S14.00-BUG-Sample databases do not persist
Given how we're creating sample DBs, the linked files are not stored in the user data directory but are instead linked to the sample files inside the binary. This results in a link to a temporary file on the machine, which disappears after some time.

Need to change how sample creation works.

### PR DESCRIPTION
**Pull request by RamiAwar**
*Issue #, if available:*  Closes  #201 

*Description of changes:* Bug happened in binaries where sample DSN was referencing a file inside the binary. 
This resulted in linking to var folders on different OSes, which are bound to get deleted.

With this change, we copy the SQLite file to the data folder on user's machine first, and then create the connection referencing that.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: frontend/src/hooks/connections.ts [hunk 1]
```diff
@@ -56,7 +56,12 @@ export function useGetConnection(id?: string) {
 }
 
 const defaultCreateErrorHandler = (err: Error) => {
-  if (!isAxiosError(err)) {
+  if (isAxiosError(err) && err.response?.status === 404) {
```
Comment (anthony2261) [inline frontend/src/hooks/connections.ts:59]: When would it return a 404? If `sample_name` is not one of the samples we have, it'll be a 422
